"use client";

import { useEffect, useState } from "react";

type ArticleRow = { id: string; kitab: string; pasal: number; title: string; summary: string | null; tags: string[]; author: string; date: string; content: string; status: string };

export default function AdminArticlesPage() {
  const [articles, setArticles] = useState<ArticleRow[]>([]);
  const [editing, setEditing] = useState<ArticleRow | null>(null);
  const [message, setMessage] = useState("");
  async function load() { const response = await fetch("/api/admin/articles"); const result = await response.json(); if (response.ok) setArticles(result.articles); else setMessage(result.error ?? "Gagal memuat artikel."); }
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, []);
  async function remove(id: string) { if (!window.confirm("Hapus artikel ini?")) return; const response = await fetch("/api/admin/articles", { method: "DELETE", headers: { "content-type": "application/json" }, body: JSON.stringify({ id }) }); if (!response.ok) { setMessage("Gagal menghapus artikel."); return; } setMessage("Artikel dihapus."); await load(); }
  async function save() { if (!editing) return; const response = await fetch("/api/admin/articles", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: editing.id, content: editing.content, publish: editing.status === "published" }) }); const result = await response.json(); if (!response.ok) { setMessage(result.error ?? "Gagal menyimpan artikel."); return; } setEditing(null); setMessage("Artikel diperbarui."); await load(); }
  return <main className="mx-auto w-full max-w-6xl px-4 py-10 sm:px-6 lg:px-8"><div className="mb-8"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[var(--accent)]">GOXPOSISI Admin</p><h1 className="mt-3 text-3xl font-semibold text-[var(--foreground)]">Daftar artikel</h1></div>{editing && <section className="glass-panel mb-6 rounded-2xl p-5"><h2 className="text-lg font-semibold text-[var(--foreground)]">Edit artikel: {editing.title}</h2><textarea value={editing.content} onChange={(event) => setEditing({ ...editing, content: event.target.value })} className="mt-4 min-h-80 w-full rounded-xl border border-[var(--border)] bg-[var(--surface-strong)] p-4 font-mono text-sm text-[var(--foreground)]" /><div className="mt-4 flex gap-2"><button onClick={save} className="rounded-xl bg-[var(--primary)] px-4 py-2 font-semibold text-white dark:text-[#071321]">Simpan</button><button onClick={() => setEditing(null)} className="rounded-xl border border-[var(--border)] px-4 py-2 text-[var(--foreground)]">Batal</button></div></section>}<div className="glass-panel overflow-x-auto rounded-2xl p-4"><table className="w-full min-w-[680px] text-left text-sm"><thead className="border-b border-[var(--border)] text-[var(--muted)]"><tr><th className="p-3">Artikel</th><th className="p-3">Kitab</th><th className="p-3">Status</th><th className="p-3">Aksi</th></tr></thead><tbody>{articles.map((article) => <tr key={article.id} className="border-b border-[var(--border)] text-[var(--foreground)]"><td className="p-3 font-medium">{article.title}</td><td className="p-3">{article.kitab} {article.pasal}</td><td className="p-3">{article.status}</td><td className="flex gap-3 p-3"><button onClick={() => setEditing(article)} className="text-[var(--accent)] hover:underline">Edit</button><button onClick={() => remove(article.id)} className="text-red-600 hover:underline">Hapus</button></td></tr>)}</tbody></table>{!articles.length && <p className="p-6 text-sm text-[var(--muted)]">Belum ada artikel di Supabase.</p>}</div>{message && <p className="mt-4 text-sm text-[var(--muted)]">{message}</p>}</main>;
}
